image-config:
  upload-path: /Users/edwardgavinwang/IdeaProjects/github/Spring-boot-mybatis/src/main/resources/static/images/


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/test
#    initialization-mode: always
#    schema:
#      - classpath: sql/cinema.sql
#      - classpath: sql/task.sql
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  profiles:
    active: dev
    # active: prod
  messages:
    basename: i18n.login

server:
  port: 8083
  thymeleaf:
      cache: false
      prefix:

        classpath: /templates

---
server:
  port: 8080

spring:
  profiles: prod
  thymeleaf:
    cache: true

---
server:
  port: 8081

spring:
  profiles: dev
  thymeleaf:
    cache: false