spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/test
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#  发送邮件的配置文件
#  mail:
#    host: smtp.qq.com
#    username: 1228589545@qq.com
#    password: noabandon520yy
#    default-encoding: utf-8
server:
  port: 8081
  thymeleaf:
      cache: false
      prefix:
        classpath: /templates
