spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mariadb://localhost:3306/test
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  profiles:
    active: dev
  messages:
    basename: i18n.login

server:
  port: 8081
  thymeleaf:
      cache: false
      prefix:
        classpath: /templates

---
server:
  port: 8082

spring:
  profiles: prod
  thymeleaf:
    cache: true

---
server:
  port: 8084

spring:
  profiles: dev
  thymeleaf:
    cache: false